name: daylight_example
description: Get the sunset and sunrise times for a geolocation without having to access any api.
version: 0.2.0
homepage: https://github.com/renancaraujo/daylight
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  daylight:
    path: ../
